### ISSUE TITLE
Checkout Form: change questions

### ISSUE THREAD

**Issue by Byronium** [calblueprint/PHC#212]
Change questions to the following:
1. Rate your experience from 1-5. (should be array adapter) 
2. Of these services, what are your top 2 priorities? (choose from checkboxes)
3. Other comments? (this one's the same)

**Comment by lilshim** [comment]
: o I thought I fixed this. Am I supposed to do anything to close it, or do you do that?

**Comment by Byronium** [comment]
take a look at the comments me and howard made first on your code! once you fix everything and push again, i'll merge your pull request, and this linked issue will automatically close.

**Comment by lilshim** [comment]
okie dokie added the comments to variables, and deleted some strings.
