### ISSUE TITLE
Only show the last 4 digits of the SSN on the show form

### ISSUE THREAD

**Issue by negativetwelve** [calblueprint/PHC#302]
I was talking with @warrenshen and @chenhoward about this and I think you should show:

`xxx-xx-1234` on the form after searching.

Thoughts?

**Comment by sxnahm** [comment]
The search list that I saw only has the name and DOB -- or are you
referring to the Personal Info page where all of the person's info is
displayed?  If so, the SSN may need to be confirmed or updated. All digits
should be shown.

Steve Nahm

**Comment by Byronium** [comment]
Hi Steve!
While that's true, I feel like the added security layer from displaying only the last 4 digits outweighs the ability to verify and update the first 5 numbers. It's also the only option we can think of to prevent immediate identity theft in cases where a culprit gets past the login screen and screen lock. Changing the login credentials can only happen reactionarily when the phone is noticed to be stolen, during which time important information can already be taken. 
What do you think?
