### ISSUE TITLE
add "Feedback__c", "Experience__c", and "Services_Needed__c" to salesforce and heroku db

### ISSUE THREAD

**Issue by Byronium** [calblueprint/phc#337]

**Comment by Byronium** [comment]
added to salesforce.

**Comment by Byronium** [comment]
alton, have you added these to the heroku db yet?

**Comment by altonzheng** [comment]
yep

**Comment by altonzheng** [comment]
but the feature isn't tested yet. I'm not sure if the android code sends the data in the way the API expects
