### ISSUE TITLE
consider periscope.io instead of making our own admin dashboard from scratch

### ISSUE THREAD

**Issue by Byronium** [calblueprint/phc#367]
check it out it's pretty dope @chenhoward @altonzheng

**Comment by Byronium** [comment]
or simply use RailsAdmin https://github.com/sferik/rails_admin. it can also export data immediately as .csv, .txt, etc, which may be useful for the nonprofit.

**Comment by chenhoward** [comment]
Will periscope always be free.

**Comment by Byronium** [comment]
using rails admin now.
